In [1]:
import pickle 
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
pipe=pickle.load(open('pipe.pkl1','rb'))

In [9]:
test_input=np.array(['male',50,1,1,'current',32.8,6.3,230],dtype=object).reshape(1,8)

In [10]:
pipe.predict(test_input)

array([1], dtype=int64)

In [11]:
test_input1=np.array(['Female',65,1,0,'never',35,4.8,190],dtype=object).reshape(1,8)

In [12]:
pipe.predict(test_input1)

array([0], dtype=int64)

In [13]:
test_input2=np.array(['Female',44,0,0,'former',31,6.5,100],dtype=object).reshape(1,8)

In [14]:
pipe.predict(test_input2)

array([0], dtype=int64)

In [15]:
test_input3=np.array(['Female',44,1,1,'No Info',34,7.0,230],dtype=object).reshape(1,8)

In [16]:
pipe.predict(test_input3)

array([1], dtype=int64)

In [37]:
test_input4=np.array(['male',37,1,1,'never',32.5,6.6,200],dtype=object).reshape(1,8)
pipe.predict(test_input4)

array([1], dtype=int64)